In [6]:
%load_ext autoreload
%autoreload 2

import numpy as np
import sys

sys.path.insert(0,"/home/hugo/OneDrive/Estudos/Mestrado_PPGES_UPE/PROJETO/PVIA_research/")

from mlopt.mlopt.optimizers.ACO import ACO

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
def rastrigin(X, *args):
    return sum(list(map(lambda x: x**2 - 10*np.cos(2*np.pi*x) - 10, list(X))))

In [11]:
X = [np.arange(-12,12,0.2), np.arange(-12,12,0.2)]

In [12]:
ACOsearch = ACO(1, 1, 0.5, 1)
ACOsearch.optimize(5, 5, X, rastrigin, verbose=True)

dimentions Ranges passed:  [array([-1.20000000e+01, -1.18000000e+01, -1.16000000e+01, -1.14000000e+01,
       -1.12000000e+01, -1.10000000e+01, -1.08000000e+01, -1.06000000e+01,
       -1.04000000e+01, -1.02000000e+01, -1.00000000e+01, -9.80000000e+00,
       -9.60000000e+00, -9.40000000e+00, -9.20000000e+00, -9.00000000e+00,
       -8.80000000e+00, -8.60000000e+00, -8.40000000e+00, -8.20000000e+00,
       -8.00000000e+00, -7.80000000e+00, -7.60000000e+00, -7.40000000e+00,
       -7.20000000e+00, -7.00000000e+00, -6.80000000e+00, -6.60000000e+00,
       -6.40000000e+00, -6.20000000e+00, -6.00000000e+00, -5.80000000e+00,
       -5.60000000e+00, -5.40000000e+00, -5.20000000e+00, -5.00000000e+00,
       -4.80000000e+00, -4.60000000e+00, -4.40000000e+00, -4.20000000e+00,
       -4.00000000e+00, -3.80000000e+00, -3.60000000e+00, -3.40000000e+00,
       -3.20000000e+00, -3.00000000e+00, -2.80000000e+00, -2.60000000e+00,
       -2.40000000e+00, -2.20000000e+00, -2.00000000e+00, -1.80000000e+0

  0%|          | 0/5 [00:00<?, ?it/s]/home/hugo/OneDrive/Estudos/Mestrado_PPGES_UPE/PROJETO/PVIA_research/mlopt/mlopt/optimizers/ACO.py:153: RuntimeWarning: divide by zero encountered in true_divide
  Pij = (Tij**alpha)/(Dij**beta)
/home/hugo/OneDrive/Estudos/Mestrado_PPGES_UPE/PROJETO/PVIA_research/mlopt/mlopt/optimizers/ACO.py:155: RuntimeWarning: invalid value encountered in true_divide
  Pij = Pij / row_sums[:, np.newaxis]
100%|██████████| 5/5 [00:00<00:00, 53.46it/s]

Setting fitness for
[11  7]
fitness is
130.0
Setting fitness for
[10  5]
fitness is
85.0
Setting fitness for
[ 8 -8]
fitness is
88.0
Setting fitness for
[7 5]
fitness is
34.0
Setting fitness for
[-1  0]
fitness is
-39.0
Setting fitness for
[0 3]
fitness is
-31.0
Setting fitness for
[-3  0]
fitness is
-31.0
Setting fitness for
[-3 -7]
fitness is
18.0
Setting fitness for
[-3  5]
fitness is
-6.0
Setting fitness for
[-3 -9]
fitness is
50.0
Dij: 
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
Tij: 
[[10.5]
 [ 0.5]
 [ 0.5]
 ...
 [ 0.5]
 [ 0.5]
 [ 0.5]]
Pij:
[[1.7213665e-03]
 [8.1969840e-05]
 [8.1969840e-05]
 ...
 [8.1969840e-05]
 [8.1969840e-05]
 [8.1969840e-05]]
Ant 0 possibilities:
[    0     1     2 ... 14397 14398 14399]
Ant 0 move from 14257 to 13201
Ant 1 possibilities:
[    0     1     2 ... 14397 14398 14399]
Ant 1 move from 12498 to 8899
Ant 2 possibilities:
[    0     1     2 ... 14397 14398 14399]
Ant 2 move from 6304 to 1929
Ant 3 possibilities:
[    0     1     2 ... 14397 14398 1439

(array([-1,  0]), -39.0)

In [9]:
Pij = ACOsearch._Pij

In [10]:
Pij[~np.isnan(Pij)]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)